/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring;

import org.junit.Test;

public class ApplicationTest {
    @Test
    public void testAppHasAGreeting() {

    }
}
